name: workshop-ci-cd
services:
  app:
    container_name: "app-${USERNAME}"
    env_file:
      - .env
    image: ghcr.io/${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - private-network

  postgres:
    container_name: "postgres-${USERNAME}"
    env_file:
      - .env
    image: postgres:17
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - private-network

volumes:
  postgres-volume:
    driver: local

networks:
  private-network:
    driver: bridge